name: web
description: Sample webpage

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.7+210313.1

environment:
  sdk: ">=2.12.0-259.12.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.2
  carousel_slider: ^4.0.0-nullsafety.0
  fluentui_system_icons: ^1.1.106
  adaptive_breakpoints: ^0.0.3

  http: ^0.13.0

  url_strategy: ^0.2.0

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/cover.r2.png
    - assets/images/logo.png
    - assets/images/logo_transparent.png
    - assets/images/tech/flutter.jpg
    - assets/images/tech/kotlin.png
    - assets/images/tech/vue.png
    - assets/images/tech/firebase.png
    - assets/images/tech/nodejs.png
    - assets/images/tech/reactjs.png
    - assets/images/tech/django.png

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
